name: Verify state

on:
  push:
  pull_request:
    types: [ opened, ready_for_review, review_requested, edited ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --build-cache shadowJar
      - name: Test with Gradle
        run: ./gradlew test
